### PR TITLE
Corrects paths for spec to be from the root

### PR DESCRIPTION
**Pull request by Romanx**
This fixes the spec route to be from the pinned version using the git submodules. Seems that changing the folder structure broke them as they're relative links.

The test failures we coming from changes to the spec since the pinned version. The failures were due to the way the project creates the test classes and types it expects the data to be in not being correct. I don't think it's a vital issue and don't really want to fix it since it's not *broken*. If you'd like to bump the spec version however as part of your changes then feel free 👍

### CODE REVIEW

**Comment by tintoy** [comment]
Awesome - thanks, @Romanx!

**Comment by tintoy** [comment]
Hi @Romanx, just gave this a try, and some of those tests fail - but I'm not sure if they're even supposed to pass (e.g. the "Not Implemented" ones)?

```
Build started, please wait...
Build completed.

Test run for D:\Development\github\tintoy\Nustache\test\Nustache.Compilation.Tests\bin\Debug\netcoreapp2.0\Nustache.Compilation.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.8.0.0: Test execution started
Running all tests in D:\Development\github\tintoy\Nustache\test\Nustache.Compilation.Tests\bin\Debug\netcoreapp2.0\Nustache.Compilation.Tests.dll
NUnit3TestExecutor converted 137 of 137 NUnit test cases
Not Run  It_supports_Enumerating_Generic_Dictionaries
Error Message:
 Not implemented

Not Run  It_supports_Generic_Dictionaries_As_Sections
Error Message:
 Not implemented

Not Run  It_supports_Generic_Dictionaries_with_missing_keys
Error Message:
 For integer types this is returning default value instead of empty string

Not Run  It_should_handle_null_callback_values
Error Message:
 Not sure if this is imporant (the callback function does the null checks currently)

Not Run  Partials(Recursion)
Error Message:
 Unsupported: Compiled recursive templates will be supported in a later release

Failed   Sections(Falsey)
Error Message:
   JSON object rendering failed for Falsey sections should have their contents omitted.
  Expected string length 2 but was 30. Strings differ at index 1.
  Expected: """"
  But was:  ""This should not be rendered.""
  ------------^

Stack Trace:
at Nustache.Core.Tests.Mustache_Spec.Official_Specs.RunMustacheSpecs(MustacheTest test) in D:\Development\github\tintoy\Nustache\test\Nustache.Compilation.Tests\Mustache_Spec\Official_Specs.cs:line 63
at Nustache.Core.Tests.Mustache_Spec.Official_Specs.Sections(MustacheTest test) in D:\Development\github\tintoy\Nustache\test\Nustache.Compilation.Tests\Mustache_Spec\Official_Specs.cs:line 13

Failed   Sections(Nested (Falsey))
Error Message:
   JSON object rendering failed for Nested falsey sections should be omitted.
  Expected string length 8 but was 13. Strings differ at index 4.
  Expected: "| A  E |"
  But was:  "| A B C D E |"
  ---------------^

Stack Trace:
at Nustache.Core.Tests.Mustache_Spec.Official_Specs.RunMustacheSpecs(MustacheTest test) in D:\Development\github\tintoy\Nustache\test\Nustache.Compilation.Tests\Mustache_Spec\Official_Specs.cs:line 63
at Nustache.Core.Tests.Mustache_Spec.Official_Specs.Sections(MustacheTest test) in D:\Development\github\tintoy\Nustache\test\Nustache.Compilation.Tests\Mustache_Spec\Official_Specs.cs:line 13

Failed   Sections(Dotted Names - Falsey)
Error Message:
   JSON object rendering failed for Dotted names should be valid for Section tags.
  Expected string length 8 but was 12. Strings differ at index 1.
  Expected: """ == """
  But was:  ""Here" == """
  ------------^

Stack Trace:
at Nustache.Core.Tests.Mustache_Spec.Official_Specs.RunMustacheSpecs(MustacheTest test) in D:\Development\github\tintoy\Nustache\test\Nustache.Compilation.Tests\Mustache_Spec\Official_Specs.cs:line 63
at Nustache.Core.Tests.Mustache_Spec.Official_Specs.Sections(MustacheTest test) in D:\Development\github\tintoy\Nustache\test\Nustache.Compilation.Tests\Mustache_Spec\Official_Specs.cs:line 13

NUnit Adapter 3.8.0.0: Test execution complete

Total tests: 137. Passed: 129. Failed: 3. Skipped: 0.
Test Run Failed.
Test execution time: 1.3858 Seconds
```

**Comment by tintoy** [comment]
The `Sections` tests are more problematic I suspect...

**Comment by Romanx** [comment]
@tintoy Perhaps the method running them is causing some differences to occur. How are you running the tests? Using dotnet test?

**Comment by tintoy** [comment]
Yep - do they pass for you? If so, must be some shared state somewhere causing a race...

**Comment by Romanx** [comment]
@tintoy yeah they were all passing for me (except the skipped tests) not sure If it's the version of NUnit or something similar as I was running them through VS. I'll try dotnet test and let you know.

**Pull request merged**
